### ISSUE TITLE
proc/diskstats is 404

### ISSUE THREAD

**Issue by paulirish** [scoutapp/scout_realtime#12]
checking the log file i'm seeing this:

```
#############################################################################Errno::ENOENT: No such file or directory - /proc/diskstats
#############################################################################Errno::ENOENT: No such file or directory - /proc/diskstats
#############################################################################Errno::ENOENT: No such file or directory - /proc/diskstats
```

**Comment by itsderek23** [comment]
Sorry @paulirish. What OS are you using? OSX/Darwin by chance?

**Comment by paulirish** [comment]
Nah running it on a debian box.

**Comment by itsderek23** [comment]
Sorry - scout_realtime doesn't support Debian as those starts are read from `/proc`, which doesn't exist there. 

We don't have immediate plans to add support for Debian. We don't use either, so we wouldn't be the best at adding initial support. 

However, we're happy to review/help. The metric collection is done via the [server_metrics gem](https://github.com/scoutapp/server_metrics). See the different collector classes (memory, disk, processes, etc).

We'll update the homepage to make OS support clear. Sorry for false start.

**Comment by paulirish** [comment]
Ah! I see.

Well it actually works fairly well (from what I can tell) with the exception of disk usage.

Thx anyhow. Nice app!

**Comment by itsderek23** [comment]
> Well it actually works fairly well (from what I can tell) with the exception of disk usage.

Cool - thanks for the heads up @paulirish.
