### ISSUE TITLE
Does not work when ran in an Nginx subfolder

### ISSUE THREAD

**Issue by warcode** [scoutapp/scout_realtime#18]
https://domain.com/scout - does not work due to trying to access domain.com/javascripts and domain.com/images instead of /scout/images.

**Comment by andre** [comment]
It's designed to be it's own self-contained web server ... I think placing it in an another web server's folder will give unpredictable results.

**Comment by warcode** [comment]
Im sure other people use nginx to proxy other web servers too, but if you are unwilling to even look into it its not much I can do.

**Comment by jamesmoriarty** [comment]
Same problem. I just have it respond to another sub domain now.

**Comment by andre** [comment]
@warcode , @jamesmoriarty, we don't use nginx here, so I'm not sure I understand your setup. Your intent is to access scout_realtime through yourdomain.com/some_subfolder - do I have that right? Can you share your nginx configuration related to scout_realtime? Are you accessing realtime on its own port, or through port 80?

**Comment by warcode** [comment]
Yes.

The site is a default https/443 config containing:

location /scout {
      proxy_pass    http://localhost:5555;
}

Which loads but then tries to access files on domain/\* instead of
domain/scout/*.

**Comment by andre** [comment]
I've merged the relative paths fix into a prerelease. Mind trying this out?

```
gem install scout_realtime --pre  # should get v1.0.3.pre
scout_realtime stop # if already running
scout_realtime start
```

**Comment by itsderek23** [comment]
scout_realtime -v1.0.3 has been released with this update.

**Comment by warcode** [comment]
Can confirm that it works for my setup. Thank you!

**Comment by warcode** [comment]
Somehow seems to be broken again with nginx 1.6.0.
Once again points to the root instead of the /scout/ location / proxy pass.

**Comment by w00kie** [comment]
I run nginx 1.7.0 with the latest release of scout_realtime and I have no issues.

My nginx config is as follows:

``` nginx
upstream scout_realtime {
        server 127.0.0.1:5555;
}

server {
        listen 443 ssl spdy;
        listen [::]:443 ssl spdy;

        location ^~ /scout/ {
                proxy_pass http://scout_realtime/;
        }
}
```

**Comment by warcode** [comment]
No longer works:

```
location /scout {
    proxy_pass http://scout_realtime/;
}
```

Still works:

```
location /scout/ {
    proxy_pass http://scout_realtime/;
}
```

I'm assuming nginx changed how they were handling no trailing slash.

**Comment by gigibiffi84** [comment]
@warcode  i just tried your suggest and i completely agree: location and proxy_pass without slash is no more working
