### ISSUE TITLE
This isn't a replacement for top.

### ISSUE THREAD

**Issue by merisbahti** [scoutapp/scout_realtime#19]
Htop is.

Unix programs were made to be single-purpose, this has similar functions to top + some other functions ductaped to it.

Hence
    "30 years ago, top was born. scout_realtime is top for the modern developer."
is incorrect.

**Comment by itsderek23** [comment]
Thanks for the feedback. We won't be changing the tagline - it's a close-enough analogy.

**Comment by toupeira** [comment]
It's different enough that it doesn't do a single thing I usually use `top` for, mainly because it shows _groups_ of processes. Also basic information like PIDs is missing.
