### ISSUE TITLE
Fonts not loading properly

### ISSUE THREAD

**Issue by emgee3** [scoutapp/scout_realtime#22]
Typekit ID is hard coded here: https://github.com/scoutapp/scout_realtime/blob/master/lib/scout_realtime/web/views/layout.erb#L25

which won't work because individual kits are associated with specific domains. 

Not sure if Proxima Nova is actually used in the page, but one could use Montserrat from Google's web fonts.

**Comment by itsderek23** [comment]
Thanks @emgee3. I forgot to remove typekit - Proxima Nova isn't being used. 

I remove it in 733452890733e2358905885470ef44cf0f620bea
