### ISSUE TITLE
It is not able to monitor docker container 

### ISSUE THREAD

**Issue by tanmally** [scoutapp/scout_realtime#30]
It doesn't work inside docker container , does it support lxc ?

Error in log :  df: cannot read table of mounted file systems

**Comment by itsderek23** [comment]
@tanmally,

Sorry for the issues - do you see any output in the `~/.scout/scout_realtime.log` log file?

**Comment by tanmally** [comment]
Pasting log content :

==> s.log <==
Starting scout_realtime service...
I, [2014-03-13T21:03:09.089905 #160]  INFO -- : starting web server
I, [2014-03-13T21:03:09.090161 #160]  INFO -- : starting stats collector thread
/var/lib/gems/2.1.0/gems/server_metrics-1.2.2/lib/server_metrics/collectors/memory.rb:125: warning: Insecure world writable dir /usr/local/sbin in PATH, mode 040777
[2014-03-13 21:03:09] INFO  WEBrick 1.3.1
[2014-03-13 21:03:09] INFO  ruby 2.1.0 (2013-12-25) [x86_64-linux-gnu]
== Sinatra/1.4.4 has taken the stage on 4055 for production with backup from WEBrick
[2014-03-13 21:03:09] INFO  WEBrick::HTTPServer#start: pid=160 port=4055
df: cannot read table of mounted file systems: No such file or directory

**Comment by tanmally** [comment]
I think it is not able to find mtab - 'grep -v rootfs /proc/mounts > /etc/mtab'
 fixed the issue at my end .Can this be sorted out at code level ?. May be information apart from disk should be available

**Comment by itsderek23** [comment]
Thanks @tanmally. We haven't explicitly tested this on a Docker Container.

It's something that would be good to support, but won't be on our immediate list. We are happy to take/help with a pull request though.

**Comment by tanmally** [comment]
Using  scout_realtime for monitoring docker was not correct as we need to get the details from lxc files ,  scout_realtime can monitor only the docker host and not containers . Sorry for the confusion !!
