### ISSUE TITLE
launch failure

### ISSUE THREAD

**Issue by selfagency** [scoutapp/scout_realtime#34]
when i run scout_realtime, i get this:

/usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require': no such file to load -- json (LoadError)

from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
from /usr/lib/ruby/gems/1.8/gems/scout_realtime-1.0.2/lib/scout_realtime.rb:23
from /usr/lib/ruby/gems/1.8/gems/scout_realtime-1.0.2/bin/scout_realtime:4:in`load'
from /usr/lib/ruby/gems/1.8/gems/scout_realtime-1.0.2/bin/scout_realtime:4
from /usr/bin/scout_realtime:23:in `load'
from /usr/bin/scout_realtime:23

**Comment by andre** [comment]
try `gem install json` then re-running scout_realtime.

**Comment by gregfr** [comment]
I have the same error although json is installed:
$ gem list  
**\* LOCAL GEMS **\*  
json (1.8.1)

**Comment by gregfr** [comment]
I re-installed with gem install scout_realtime and now it's starting
