### ISSUE TITLE
Error to show information in Mac OSX 10.7

### ISSUE THREAD

**Issue by leolelego** [scoutapp/scout_realtime#35]
Hello,

if have this error when i run scout_reatime on my Mac (10.7.5, ruby 2.2.1 and same on ruby 2.0) : 
<code>
Errno::ENOENT: No such file or directory @ rb_sysopen - /proc/diskstats
</code>
I'm not ruby developer, i understand the sence of the sentence, but how i can solve this problem ?

This may cause  : missing informations in my webview like no : CPU info, no Disk Info, no process info.

**Comment by itsderek23** [comment]
@leolelego,

scoutapp/server_metrics@a1ff0d756899d56d637fb4a715ea2183351f297d adds error-handling for OSX. 

Note that we're not able to grab the full array of metrics on OSX that we can on other Linux flavors because of the absence of the `/proc` system.

**Comment by itsderek23** [comment]
Sorry - to fix this:

`gem install server_metrics`
`scout_realtime stop`
`scout_realtime`
