### ISSUE TITLE
Make Scout listen on localhost

### ISSUE THREAD

**Issue by tadev** [scoutapp/scout_realtime#36]
Can we make scout only listen on localhost instead of openly on the web?
This would fix many problems...

First of all, we could provide reverse proxy scripts.
Others can use scout by setting up an ssh tunnel.

Atleast an option to which IP to bind to would be awesome.
Thanks

**Comment by itsderek23** [comment]
This isn't something we have immediate plans of implementing, but we're happy to look at a pull request for this functionality.

**Comment by itsderek23** [comment]
Merged! See 63e5ef1.
