### ISSUE TITLE
SSH Tunnel Hangs?

### ISSUE THREAD

**Issue by itsderek23** [scoutapp/scout_realtime#4]
The instructions list an SSH tunnel as option to access the realtime UI:

<pre>
ssh -NL 5555:localhost:5555 user@ip_or_hostname
</pre>

However, this seems to hang when accessing a server using IPTables where this port isn't exposed. Am I missing something obvious?

**Comment by andre** [comment]
It's some issue specific to the port number, but I don't know why.

Here are some combos that work:
- `ssh -NL 5000:localhost:6666 user@remote` (running the daemon on port 6666, and hitting `localhost:5000` in your browser)
- `ssh -NL 7777:localhost:77 user@remote` (same port locally on both ends: running the daemon on port 7777, and hitting `localhost:7777` in your browser

Generally speaking, if your local port 5555 is tied up (as it often is in realtime development), just forward a different local port to remote port 5555: 
- `ssh -NL 7777:localhost:5555 user@remote` - daemon is running on the default 5555 port on the remote box, but you access it with `localhost:7777`, so you can still hit localhost:5555 for your development instance.
