### ISSUE TITLE
GPU monitoring

### ISSUE THREAD

**Issue by franklinr** [scoutapp/scout_realtime#54]
Hi,
  I would like to use scout realtime to monitor my GPU usage.  There is nvidia command that will produce various stats about my gpu and I can pull out the GPU usage.

```
> nvidia-smi -a | grep "Gpu"
        Gpu                         : 0 %
```

Is there a simple way to add some scout monitor based on a unix command?

**Comment by dlanderson** [comment]
Sorry @franklinr this is not implemented in scout realtime.
