### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by seanabraham** [scoutapp/scout_realtime#8]
After running scout_realtime I visit the page and receive "Internal Server Error".

It looks like it has something to do with this:

NoMethodError - undefined method `each_with_object' for ["cpu", "memory", "disk", "network", "processes"]:Array

**Comment by seanabraham** [comment]
Line number:

usr/lib64/ruby/gems/1.8/gems/scout_realtime-1.0.0/lib/scout_realtime/web_app.rb:38:in `GET /'

**Comment by andre** [comment]
@SeanA208, it currently requires Ruby 1.9.3 -- I believe you'll get that error on Ruby 1.8.

**Comment by andre** [comment]
FYI, I added a real error message on the command line when running under Ruby 1.8.
