### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by ghost** [scoutapp/scout_realtime#9]
Hello,
It doesn't work well on FreeBSD. Too bad :/
It works like this : http://i.imgur.com/ugt0rJZ.png

**Comment by Petah** [comment]
Debian support would be nice too.

**Comment by itsderek23** [comment]
We don't have immediate plans to add support for FreeBSD or Debian. We don't use either, so we wouldn't be the best at adding initial support. 

However, we're happy to review/help. The metric collection is done via the [server_metrics gem](https://github.com/scoutapp/server_metrics). See the different collector classes (memory, disk, processes, etc).
